name: Create Release
on:
  push:
    branches:
      - main
jobs:
  release:
    #
    # Create a GitHub Release based on conventional commits.
    #
    name: 'Release to GitHub'
    runs-on: ubuntu-latest
    steps:
      # Checkout code to release.
      - name: Checkout repo
        uses: actions/checkout@v3
      # Setup Node needed to create release.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Add plugin to make the changelog for the release.
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      # Create the release.
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GIT_AUTHOR_NAME: release-bot
          GIT_AUTHOR_EMAIL: release@test.com
          GIT_COMMITTER_NAME: asyncapi-bot
          GIT_COMMITTER_EMAIL: info@asyncapi.io
        run: npx semantic-release
